title: Jose Alejandro Garcia Cifuentes # your name (or website title) here
logo: "Sin título.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <em>I have been around computers for as long as I can remember, that is the reason my life has brought me into this area. Also, I have spent most of my time learning by myself so I could consider myself as a self taught dev, something that has helped me a lot in learning new languages or interfaces quicker than the average. <br>I am always willing to help and excited about learning new features so I can get to know every bit of it! </em>     
  <br><br>
  <a href="https://www.linkedin.com/in/josealejandrogarciacifuentes/">Linkedin</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
